### ISSUE TITLE
Unable to load timeline

### ISSUE THREAD

**Issue by yossiha** [fabfuel/prophiler#54] opened 2016-02-05 01:16 UTC
Hey,
I'm using Phalcon Framework 2.1.0 BETA 2, with a multi-module application. 
When I enable the plugin manager I get an error (it works without the timeline..)..

Any ideas why this happens? :)

> Phalcon\Mvc\Dispatcher\Exception: SessionController handler class cannot be loaded
> # 0    Phalcon\Mvc\Dispatcher->_throwDispatchException(SessionController handler class cannot be loaded, 2)
> # 1    Phalcon\Dispatcher->dispatch()
> # 2    Phalcon\Mvc\Application->handle()

My index.php code is:

```
$profiler = new \Fabfuel\Prophiler\Profiler();
$di->set('profiler', $profiler, true);

$toolbar = new \Fabfuel\Prophiler\Toolbar($profiler);
$toolbar->addDataCollector(new \Fabfuel\Prophiler\DataCollector\Request());
$pluginManager = new \Fabfuel\Prophiler\Plugin\Manager\Phalcon($profiler);
$pluginManager->register();

//register modules here..

echo $application->handle()->getContent();
echo $toolbar->render();
```

On another configuration file (loaded before the profiler):

```
if(DEBUG) {
    $di->set('dispatcher', function () use ($di) {
        $dispatcher = new \Phalcon\Mvc\Dispatcher();
        $dispatcher->setEventsManager($di->get('eventsManager'));
        return $dispatcher;
    }, true);
}]
```

**Comment by fabfuel** [comment] 2016-02-21 07:25
Unfortunately I'm unable to reproduce this problem.

Instead of registering the whole PluginManager with `register()`, try to register the plugins separately, maybe that helps you to find out what exactly causes the problem:

https://github.com/fabfuel/prophiler/blob/develop/src/Fabfuel/Prophiler/Plugin/Manager/Phalcon.php#L32

Best
Fabian

**Comment by fabfuel** [comment] 2017-01-04 06:33
Closing this for now

**Closed by fabfuel** 2017-01-04 06:33 UTC
Labels: invalid
